environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Create temp directory
  - ps: New-Item -ItemType directory -Path c:\temp
  # Install python
  - cinst python2
  # Refresh environment variables. Add python to path
  - cmd: refreshenv
  # Install gcloud sdk
  - ps: Invoke-WebRequest https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe -OutFile c:\temp\GoogleCloudSDKInstaller.exe
  - cmd: c:\temp\GoogleCloudSDKInstaller.exe /S /singleuser /noreporting /nostartmenu /nodesktop
  # Refresh environment variables. Add google-cloud-sdk to path
  - cmd: refreshenv
  # Install datastore emulator component
  - cmd: "'C:\\Program Files\\Google\\Cloud SDK\\google-cloud-sdk.staging\\bin\\gcloud' components install cloud-datastore-emulator"
  # Install node.js versions
  - ps: Install-Product node $env:nodejs_version $env:platform
  # Install npm dependencies
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off