name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Docker pull google/cloud-sdk:latest
        run: docker pull google/cloud-sdk:latest

      - name: Install locally the Gloud sdk
        run: sudo sh ./scripts/install-cloud-sdk.sh

      - name: Install dependencies
        run: npm install

      - name: Install @google-cloud/datastore peer dependency
        run: npm install --no-save @google-cloud/datastore

      - name: Run test
        run: npm test
