name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [14, 16, 18, 19]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-package: jre
          java-version: 11

      - name: Docker pull google/cloud-sdk:latest
        run: docker pull --quiet google/cloud-sdk:latest
        if: runner.os == 'Linux'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Update GCloud Components
        run: gcloud components update --quiet

      - name: Install GCloud beta
        run: gcloud components install beta --quiet

      - name: Install cloud-datastore-emulator
        run: gcloud components install cloud-datastore-emulator --quiet

      - name: Install dependencies
        run: npm install

      - name: Install @google-cloud/datastore peer dependency
        run: npm install --no-save @google-cloud/datastore

      - name: Run test
        timeout-minutes: 15
        run: npm test
